### ISSUE TITLE
Issue with Sodium (encryption from earlier adapter version)

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.roomba#4]
I also see following issue in the log, related to roomba adapter:

> ```
> 2019-01-10 17:08:26.429  - ESC[32minfoESC[39m: host.raspberrypi object change system.adapter.roomba.0
> 2019-01-10 17:08:26.442  - ESC[32minfoESC[39m: host.raspberrypi instance system.adapter.roomba.0 started with pid 10931
> 2019-01-10 17:08:29.070  - ESC[31merrorESC[39m: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.roomba/library.js:36
> 2019-01-10 17:08:29.070  - ESC[31merrorESC[39m: Caught by controller[0]:                return _sodium.to_hex(_sodium.crypto_secretbox_keygen());
> 2019-01-10 17:08:29.070  - ESC[31merrorESC[39m: Caught by controller[0]:                                              ^
> 2019-01-10 17:08:29.070  - ESC[31merrorESC[39m: Caught by controller[0]: TypeError: _sodium.crypto_secretbox_keygen is not a function
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at Library.getEncryptionKey (/opt/iobroker/node_modules/iobroker.roomba/library.js:36:33)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.roomba/main.js:137:21)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at Adapter.emit (events.js:188:13)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:25)
> 2019-01-10 17:08:29.071  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-parser/index.js:251:12)
> 2019-01-10 17:08:29.072  - ESC[31merrorESC[39m: Caught by controller[0]:     at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:335:16)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:456:14)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at WS.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:273:10)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: Caught by controller[0]:     at WS.Transport.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
> 2019-01-10 17:08:29.073  - ESC[31merrorESC[39m: host.raspberrypi instance system.adapter.roomba.0 terminated with code 1 ()
> 
> ```

_Originally posted by @antondnateam in https://github.com/Zefau/ioBroker.roomba/issues/3#issuecomment-453117041_

**Comment by Zefau** [comment]
For it is working with the current version from Github.
Please try the following (uninstall, install, add instance, upload instance):

```
iobroker del roomba
iobroker url https://github.com/Zefau/ioBroker.roomba
iobroker add roomba
iobroker upload roomba
```

**Comment by Zefau** [comment]
Is it fixed?
