### ISSUE TITLE
Roomba 980 - TypeError: Cannot read property 'time' of null

### ISSUE THREAD

**Issue by ISaneI** [Zefau/ioBroker.roomba#7]
Trying to get the Roomba 980 running, with no success. Its able to connect to the Roomba but then I get this:
```
host.iobroker	2019-02-09 14:45:45.528	info	Restart adapter system.adapter.roomba.0 because enabled
host.iobroker	2019-02-09 14:45:45.528	error	instance system.adapter.roomba.0 terminated with code 0 (OK)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at ontimeout (timers.js:498:11)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at Timeout.setInterval [as _onTimeout] (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/lib/v2/local.js:38:16)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at MqttClient.emit (events.js:211:7)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at emitOne (events.js:116:13)
host.iobroker	2019-02-09 14:45:45.528	error	Caught by controller[0]: at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roomba/main.js:310:17)
host.iobroker	2019-02-09 14:45:45.527	error	Caught by controller[0]: TypeError: Cannot read property 'time' of null
roomba.0	2019-02-09 14:45:44.699	info	Roomba online. Connection established.
roomba.0	2019-02-09 14:45:42.166	info	Connecting to Roomba..
roomba.0	2019-02-09 14:45:42.165	info	starting. Version 0.4.1 in /opt/iobroker/node_modules/iobroker.roomba, node: v8.15.0
host.iobroker	2019-02-09 13:45:40.976	info	instance system.adapter.roomba.0 started with pid 21639
host.iobroker	2019-02-09 13:45:40.969	info	object change system.adapter.roomba.0
host.iobroker	2019-02-09 13:45:20.797	info	Do not restart adapter system.adapter.roomba.0 because disabled or deleted
host.iobroker	2019-02-09 13:45:20.797	error	instance system.adapter.roomba.0 terminated with code 3 (Adapter disabled or invalid config)
```
Running on: Ubuntu Server 18.04.1 LTS
Roomba SW: v2.4.6-3

not sure if Im doing something wrong ..

**Comment by Zefau** [comment]
Fixed with latest commit. Could you try with current Github version using `iobroker url https://github.com/Zefau/ioBroker.roomba` ? Thanks

**Comment by ISaneI** [comment]
Thanks for the fast fix 👍
